### ISSUE TITLE
ERR_NO_RESULT: Could not extract stream for this track

### ISSUE THREAD

**Issue by Kisakay** [retrouser955/discord-player-deezer#2]
I'm using NodeJS 20.7.0

    "@discord-player/equalizer": "^0.2.2",
    "@discord-player/extractor": "^4.3.1",
    "@discord-player/utils": "^0.2.1",
    "@discordjs/voice": "^0.16.0",
    "discord-player": "^6.6.3",
    "discord-player-deezer": "^0.0.8",
    "mediaplex": "^0.0.6",
    "youtube-ext": "^1.1.12"
    
discord-player-deezer cannot play links deezer.page.link...

Error: Could not find stream source
    at _AttachmentExtractor.stream (/home/anais/Documents/GitHub/ihrz/node_modules/@discord-player/extractor/dist/index.js:1074:13)
    at /home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2502:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _ExtractorExecutionContext.run (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:1159:22)
    at async #createGenericStream (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2496:22)
    at async _GuildQueuePlayerNode.play (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2399:9)
    at async _Player.play (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:4494:9)
    
Example: https://deezer.page.link/g5NMKWr5jBkTj5Dz8

Cordialy,
Anaïs

**Comment by Kisakay** [comment]
I have update `discord-player-deezer` to 0.0.9 and `discord-player` to 6.6.4.
The error still here.

My Player:
```
let player = new Player(client, {
        ytdlOptions: {
            quality: "highestaudio",
            highWaterMark: 1 << 25
        }
    });

    await player.extractors.register(SpotifyExtractor, {});
    await player.extractors.register(SoundCloudExtractor, {});
    await player.extractors.register(DeezerExtractor, {});

    await player.extractors.loadDefault();
```

Cordially,
Anaïs

**Comment by retrouser955** [comment]
Hey, it appears that the error is coming from discord-player's default attachment extractor. Could you try unloading the attachment extractor?

**Comment by Kisakay** [comment]
```TS
    let player = new Player(client, {
        ytdlOptions: {
            quality: "highestaudio",
            highWaterMark: 1 << 25
        }
    });

    await player.extractors.register(SpotifyExtractor, {});
    await player.extractors.register(SoundCloudExtractor, {});
    await player.extractors.register(DeezerExtractor, {});

    // await player.extractors.loadDefault();
```
Now :
```TS
[29/09/2023 16:37:41 ERR]: ERR_NO_RESULT: Could not extract stream for this track

Error: Could not find a suitable source to stream from.
    at DeezerExtractor.brdgeProvider (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player-deezer/dist/DeezerExtractor.js:123:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2502:12
    at async _ExtractorExecutionContext.run (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:1159:22)
    at async #createGenericStream (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2496:22)
    at async _GuildQueuePlayerNode.play (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2399:9)
    at async _Player.play (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:4494:9)
```

URL: https://deezer.page.link/nJPXk1oUjjvrCBN99


Cordially,
Anaïs

**Comment by retrouser955** [comment]
I will investigate this!

**Comment by retrouser955** [comment]
It seems to be an error with `@mithron/deezer-music-metadata` not loading the Deezer share links properly. I will try to make a direct API request.

**Comment by retrouser955** [comment]
It should be fixed in 1.0.0

**Comment by Kisakay** [comment]
I have again this error, not fixed i think..

```TS
[04/10/2023 20:53:15 ERR]: ERR_NO_RESULT: Could not extract stream for this track
Error: Could not find stream source
    at _AttachmentExtractor.stream (/home/anais/Documents/GitHub/ihrz/node_modules/@discord-player/extractor/dist/index.js:1074:13)
    at /home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2502:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _ExtractorExecutionContext.run (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:1159:22)
    at async #createGenericStream (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2496:22)
    at async _GuildQueuePlayerNode.play (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:2399:9)
    at async _Player.play (/home/anais/Documents/GitHub/ihrz/node_modules/discord-player/dist/index.js:4494:9)
    at async Object.run (/home/anais/Documents/GitHub/ihrz/dist/src/Commands/music/!play.js:46:19)
    at async Object.run (/home/anais/Documents/GitHub/ihrz/dist/src/Commands/music/music.js:119:9)
    at async slashExecutor (/home/anais/Documents/GitHub/ihrz/dist/src/Events/interactionCreate.js:125:13)
Error: Could not find stream source
```

package.json :
```
    "@discord-player/equalizer": "^0.2.2",
    "@discord-player/extractor": "^4.3.1",
    "@discord-player/utils": "^0.2.1",
    "@discordjs/voice": "^0.16.0",
    "@mithron/deezer-music-metadata": "^1.0.3",
    "@types/crypto-js": "^4.1.1",
    "@types/express": "^4.17.17",
    "@types/js-yaml": "^4.0.5",
    "axios": "^1.4.0",
    "better-sqlite3": "^8.4.0",
    "canvas": "^2.11.2",
    "colors": "^1.4.0",
    "crypto-js": "^4.1.1",
    "date-and-time": "^3.0.2",
    "date-fns": "^2.30.0",
    "deepmerge-ts": "^5.1.0",
    "discord-backup": "^3.3.2",
    "discord-oauth2": "^2.11.0",
    "discord-player": "^6.6.4",
    "discord-player-deezer": "^1.0.0",
    "discord.js": "^14.13.0",
    "express": "^4.18.2",
    "fs": "^0.0.1-security",
    "https": "^1.0.0",
    "js-yaml": "^4.1.0",
    "mediaplex": "^0.0.6",
    "moment": "^2.29.4",
    "mongoose": "^7.3.1",
    "ms": "^3.0.0-canary.1",
    "os-utils": "^0.0.14",
    "ping": "^0.4.4",
    "process": "^0.11.10",
    "promise-mysql": "^5.2.0",
    "quick.db": "^9.1.6",
    "quickmongo": "^5.2.0",
    "serialize-javascript": "^6.0.1",
    "shelljs": "^0.8.5",
    "soundcloud-scraper": "^5.0.3",
    "sourcebin": "^5.0.0",
    "tslib": "^2.6.0",
    "typescript": "^5.1.6",
    "wait": "^0.4.2",
    "yarn": "^1.22.19",
    "youtube-ext": "^1.1.12"
```

**Comment by retrouser955** [comment]
Hey, it seems discord-player's default attachment extractor is striking again. Disable it and try again.

**Comment by retrouser955** [comment]
Hello @Kisakay, are you still having this issue? If not, I am going to close this.
